
import type { HubLink } from "$lib/interfaces";

export let defaultLinks: HubLink[] = [
  {
    label: "Emby",
    url: "http://emby.garystrousers.com",
    img: "/img/emby.svg",
    visible: true,
    catagory: "Movies and Series",
  },
  {
    label: "Netflix",
    url: "http://www.netflix.com/WiHome",
    img: "/img/netflix.svg",
    visible: true,
    catagory: "Movies and Series",
  },
  {
    label: "Stan",
    url: "https://www.stan.com.au/",
    img: "/img/stan.svg",
    visible: true,
    catagory: "Movies and Series",
  },
  {
    label: "YouTube",
    url: "https://www.youtube.com/",
    img: "/img/youtube.svg",
    visible: true,
    catagory: "Movies and Series",
  },
  {
    label: "ABC iView",
    url: "https://iview.abc.net.au/",
    img: "/img/abc.svg",
    visible: true,
    catagory: "TV Channels",
  },
  {
    label: "Seven Plus",
    url: "https://7plus.com.au/",
    img: "/img/seven.svg",
    visible: true,
    catagory: "TV Channels",
  },
  {
    label: "Nine Now",
    url: "https://www.9now.com.au/",
    img: "/img/nine.svg",
    visible: true,
    catagory: "TV Channels",
  },
  {
    label: "Ten Play",
    url: "https://10play.com.au/",
    img: "/img/ten.svg",
    visible: true,
    catagory: "TV Channels",
  },
  {
    label: "SBS On Demand",
    url: "https://www.sbs.com.au/ondemand/",
    img: "/img/sbs.svg",
    visible: false,
    catagory: "TV Channels",
  },
  {
    label: "Kayo",
    url: "https://kayosports.com.au/browse",
    img: "/img/kayo.svg",
    visible: false,
    catagory: "Sport",
  },
  {
    label: "Funimation",
    url: "https://www.funimation.com/account/#history",
    img: "/img/funimation.svg",
    visible: false,
    catagory: "Movies and Series",
  },
  {
    label: "Disney Plus",
    url: "https://www.disneyplus.com/",
    img: "/img/disney.svg",
    visible: false,
    catagory: "Movies and Series",
  },
  {
    label: "Prime Video",
    url: "https://www.primevideo.com/",
    img: "/img/primevideo.svg",
    visible: false,
    catagory: "Movies and Series",
  },
  {
    label: "BritBox",
    url: "https://www.britbox.com/au/",
    img: "/img/britbox.svg",
    visible: false,
    catagory: "Movies and Series",
  },
  {
    label: "Paramount+",
    url: "https://www.paramountplus.com/",
    img: "/img/paramount.svg",
    visible: false,
    catagory: "Movies and Series",
  },
];

